services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3000:3000"
  
  product-service:
    build:
      context: ./product-service
    ports:
      - "3001:3001"

  order-service:
    build:
      context: ./order-service
    ports:
      - "3002:3002"

  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "3003:3003"
    depends_on:
      - user-service
      - product-service
      - order-service